services:
  backend:
    container_name: backend_app 
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network
  
  frontend:
    container_name: frontend_app 
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge