version: '3.8'
services:
  jenkins: 
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  jenkins_master: